scampcat/scamp/urls.py
from django.conf.urls.defaults import url, patterns

from scampcat.scamp.views import (AnnotationDetailView, ScampDetailView, 
                                  ScampReorderView)

urlpatterns = patterns(
    'scampcat.scamp.views',
    url(r'^(?P<slug>[a-z0-9]+)/$', ScampDetailView.as_view(), 
        name="scamp_detail"),
    url(r'^(?P<slug>[a-z0-9]+)/reorder/$', ScampReorderView.as_view(), 
        name="scamp_reorder"),
    url(r'^(?P<slug>[a-z0-9]+)/tags/$', 'scamp_add_tags', 
        name="scamp_add_tags"),
    url(r'^(?P<slug>[a-z0-9]+)/claim/$', 'scamp_claim', 
        name="scamp_claim"),
    url(r'^(?P<slug>[a-z0-9]+)/clone/$', 'scamp_clone', 
        name="scamp_clone"),
    url(r'^(?P<slug>[a-z0-9]+)/toggle-lock/$', 'scamp_toggle_lock', 
        name="scamp_toggle_lock"),
    url(r'^(?P<slug>[a-z0-9]+)/tags/$', 'scamp_tags', 
        name="scamp_tags"),
    url(r'^(?P<slug>[a-z0-9]+)/flag/$', 'scamp_report', 
        name="scamp_report"),
    url(r'^(?P<slug>[a-z0-9]+)/delete/$', 'scamp_delete', 
        name="scamp_delete"),
    url(r'^(?P<scamp_slug>[a-z0-9]+)/(?P<annotation_id>[\d]+)/$',
        AnnotationDetailView.as_view(), name="annotation_detail"),
    url(r'^tags/(?P<tag>[-\w\s\.\+]+)/$', 'scamp_tags', 
        name="scamp_tags"),
    url(r'^$', 'homepage', name='homepage'),
)

scampcat/urls.py
from django.conf import settings
from django.conf.urls.defaults import url, include, patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

# Custom error handlers.
handler404 = 'scampcat.common.views.not_found_handler'
handler500 = 'scampcat.common.views.error_handler'

urlpatterns = patterns(
    '',
    url(r'^admin/sentry/', include('sentry.web.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^registration/', include('social_auth.urls')),
    url(r'^liberate/', include('scampcat.liberation.urls')),
    url(r'^user/', include('scampcat.accounts.urls')),
)

urlpatterns += patterns(
    '',
    url(r'^login/$', 'social_auth.views.auth', {'backend': 'twitter'},
        name='login'),
    url(r'^logout/$', 'scampcat.accounts.views.logout',
        name='logout'),
    url(r'^login/error/$', 'scampcat.accounts.views.login_error',
        name='login_error'),
    url(r'^404/$', 'scampcat.common.views.not_found_handler', name='404'),
    url(r'^500/$', 'scampcat.common.views.error_handler', name='500'),
)

urlpatterns += patterns(
    'django.views.generic.simple',
    url(r'^robots.txt$', 'direct_to_template', {'template': 'robots.txt',
                                                'mimetype': 'text/plain'}),
    url(r'^humans.txt$', 'direct_to_template', {'template': 'humans.txt',
                                                'mimetype': 'text/plain'}),
    url(r'^terms/$', 'direct_to_template', {'template': 'terms.html'},
        name='terms'),
    url(r'^privacy/$', 'direct_to_template', {'template': 'privacy.html'},
        name='privacy'),

)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

# Catch all and send to scamp urls.
urlpatterns += patterns(
    '',
    url(r'^', include('scampcat.scamp.urls')),
)

scampcat/scamp/forms.py
from __future__ import with_statement
import hashlib

from django import forms
from django.contrib.auth.models import AnonymousUser
from django.core.files.storage import default_storage
from taggit.forms import TagField

from scampcat.scamp.models import Annotation, Scamp, Image
from scampcat.scamp.settings import ALLOWED_MIMETYPES
from scampcat.scamp.utils import clone_scamp, download_and_validate_image


class AnnotationForm(forms.ModelForm):

    class Meta:
        model = Annotation
        fields = ('text', 'order', 'pos_x', 'pos_y', 'facing')

    def __init__(self, scamp, *args, **kwargs):
        self.scamp = scamp
        super(AnnotationForm, self).__init__(*args, **kwargs)

    def save(self, commit=True, **kwargs):
        annotation = super(AnnotationForm, self).save(commit=False, **kwargs)
        annotation.scamp = self.scamp
        if commit:
            annotation.save()
        return annotation


class ScampForm(forms.ModelForm):

    class Meta:
        model = Scamp
        fields = ('title', 'description')


class ScampCloneForm(forms.Form):
    """This form handles the cloning of a scamp;
    it also checks whether the scamp was actually
    cloneable.
    """
    scamp_to_clone = forms.IntegerField(min_value=1)

    def __init__(self, user, *args, **kwargs):
        """We need the user for saving purposes later.
        """
        self.user = user
        super(ScampCloneForm, self).__init__(*args, **kwargs)

    def clean_scamp_to_clone(self):
        """Make sure the scamp exists and is cloneable
        before trying to do so.
        """
        scamp_id = self.cleaned_data.get('scamp_to_clone')
        try:
            self.scamp = Scamp.objects.get(pk=scamp_id)
        except Scamp.DoesNotExist:
            raise forms.ValidationError("Scamp does not exist to clone.")
        else:
            if not self.scamp.is_cloneable:
                raise forms.ValidationError("Scamp is not cloneable.")
        return scamp_id

    def save(self, *args, **kwargs):
        """Carry out the cloning process and return the
        new scamp clone.
        """
        return clone_scamp(self.scamp, self.user)


class ScampUploadForm(forms.Form):
    """Form to upload an image from the local file
    system or download it via a URL. Also handles
    all the saving of said image.:
    """
    image = forms.ImageField(required=False, label="Upload from disk")
    url = forms.URLField(verify_exists=False, required=False,
                         label="Link to one")

    def __init__(self, user=None, *args, **kwargs):
        if isinstance(user, AnonymousUser):
            self.user = None
        else:
            self.user = user
        super(ScampUploadForm, self).__init__(*args, **kwargs)

    def clean_image(self):
        """Check the image is of a supported type.
        """
        image = self.cleaned_data.get('image')
        if image and not image.content_type in ALLOWED_MIMETYPES:
            types = "/".join([x for x in ALLOWED_MIMETYPES.itervalues()])
            error = "Image is not of an allowed type:  %s." % types
            raise forms.ValidationError(error)
        return image

    def clean_url(self):
        """Access the URL provided and downloads the contents,
        only returns fine if the file provided is an image.
        """
        url = self.cleaned_data.get('url')
        if url:
            self.cleaned_image_data = download_and_validate_image(url)
            if not self.cleaned_image_data['image']:
                error = "%s" % self.cleaned_image_data['message']
                raise forms.ValidationError(error)
        return url

    def clean(self):
        image_provided = self.cleaned_data.get('image')
        url_provided = self.cleaned_data.get('url')
        if image_provided and url_provided:
            raise forms.ValidationError('Please only provide either a file '
                                        '*or* a URL.')
        elif image_provided or url_provided:
            # This is the result we want, only one
            # of the two fields filled out.
            return self.cleaned_data
        else:
            raise forms.ValidationError('You must provide an image or a URL.')

    def save(self, commit=True, *args, **kwargs):
        """Creates the relevant scamp and image instances
        and saves them to the db if commit is True.
        """
        image_data = {}
        image_field = self.cleaned_data.get('image')
        if image_field:
            # Determine the filehash
            file_hash = hashlib.md5()
            # Make sure we don't choke python with a big file
            # Take advantage of the fact that MD5 has 128-byte digest blocks
            for chunk in iter(lambda: image_field.read(128), ''):
                file_hash.update(chunk)
            image_data['url_key'] = file_hash.hexdigest()
            save_path = 'scamp-images/%s.%s' % (image_data['url_key'],
                                ALLOWED_MIMETYPES[image_field.content_type])
            if default_storage.exists(save_path):
                # File exists, associate this image
                image_file = save_path
            else:
                # File doesn't exist, save it
                image_file = default_storage.save(save_path, image_field)
            image_data['image'] = image_file
        else:
            url = self.cleaned_data.get('url')
            image_data['url_key'] = hashlib.md5(url).hexdigest()
            image_data['url'] = url
            save_path = 'scamp-images/%s.%s' % (
                                          image_data['url_key'],
                                          self.cleaned_image_data['filetype'])
            if default_storage.exists(save_path):
                # File exists, associate this image
                image_file = save_path
            else:
                image_file = default_storage.save(
                    save_path, self.cleaned_image_data['image'])
            image_data['image'] = image_file
        # Create the image instance.
        image = Image(**image_data)
        if commit:
            image.save()

        # Create the scamp instance and attach the image.
        scamp_data = {'image': image}
        if self.user:
            scamp_data['user'] = self.user
        scamp = Scamp(**scamp_data)
        if commit:
            scamp.save()
        return scamp, image


class ScampTagsForm(forms.Form):
    """Form to tag a ``Scamp``"""
    tags = TagField()

scampcat/templates/base.html
<!DOCTYPE html>
<!--[if lte IE 8 ]><html lang="en" class="ie-lte-8"><![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"><!--<![endif]-->
<head>
	<meta charset="utf-8"/>
    <title>{% block title %}ScampCat{% endblock %}</title>
	<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=7,chrome=1"/><![endif]-->
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="{{ STATIC_URL }}styles/jquery-ui-1.8.14.custom.css">
	<link rel="stylesheet" href="{{ STATIC_URL }}styles/base.css">

    <link type="text/plain" rel="author" href="/humans.txt" />

	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <link href='http://fonts.googleapis.com/css?family=Coustard' rel='stylesheet' type='text/css'>
    <script>document.documentElement.className += ' js'</script>

    {% block head_tracking %}
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-25738201-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
    {% endblock %}


</head>
<body class="{% block body_classes %}{% endblock %}">
    
    <header class="site-header">
        {% if not request.path == '/' %}
            <a href="/" class="scampcat-logo"><h1>ScampCat</h1></a>
        {% endif %}
        <div class="user-bar">
        {% if request.user.is_authenticated %}
            <a href="{% url accounts_profile request.user.username %}"><img class="avatar-thumbnail" src="{{ request.user.get_profile.avatar_url }}" />{{ request.user.username }}</a> | 
            <a href="{% url logout %}">logout</a>
        {% else  %}
        <a href="{% url login %}?next={{ request.path }}">login using twitter</a>
        {% endif %}
        </div>
	</header>

	<div class="wrapper">

        {% if messages %}
            <ul id="messages" class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}<div role="button" class="close">×</div></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% block content %}
        {% endblock %}

        <footer>
            {% block footer %}
            {% endblock %}
            <div class="legal">
                &copy; <a href="http://theteam.co.uk" title="Creative Digital Agency London">theTeam</a> 2011 &bull; <a href="{% url privacy %}" title="Our Privacy Policy">Privacy</a> &bull; <a href="{% url terms %}" title="Our Term &amp; Conditions">Terms</a>.
            </div>
        </footer>
	</div>

	
	{% block body_script %}
		<script src="{{ STATIC_URL }}scripts/intro.js"></script>
		<script src="{{ STATIC_URL }}scripts/jquery-1.6.2.js"></script>
		<script src="{{ STATIC_URL }}scripts/jquery-ui-1.8.14.custom.js"></script>
		<script src="{{ STATIC_URL }}scripts/EventEmitter.js"></script>
		<script src="{{ STATIC_URL }}scripts/InlineEdit.js"></script>
		<script src="{{ STATIC_URL }}scripts/Annotation.js"></script>
		<script src="{{ STATIC_URL }}scripts/AnnotationList.js"></script>
		<script src="{{ STATIC_URL }}scripts/MarkerView.js"></script>
		<script src="{{ STATIC_URL }}scripts/Scamp.js"></script>
		<script src="{{ STATIC_URL }}scripts/base.js"></script>
	{% endblock %}
</body>
</html>

scampcat/templates/homepage.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Annotation Tool{% endblock %}
{% block body_classes %}wide homepage{% endblock %}

{% block content %}
    <h1>ScampCat</h1>
    <h2>Annotate, then share your images..</h2>
    {% if form.non_field_errors %}
        <ul class="messages">
            {% for error in form.non_field_errors %}
                <li class="danger">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form class="upload" method="POST" action="" enctype="multipart/form-data">
        <div class="field">
            <label for="id_image">Upload:</label>            
            {{ form.image }}
        </div>
        <div class="field last">
            <label for="id_url">or link:</label>            

            <div class="input">
              <div class="input-prepend">
                <span class="add-on">URL</span>
                {{ form.url }}
              </div>
            </div>

        </div>
        {% csrf_token %}
        <button type="submit" class="custom go">Submit</button>
    </form>
{% endblock %}

scampcat/templates/lolcat.html
<p>Here is a cat picture instead!</p>

{% if object %}
<a href="{{ object.url }}" title="{{ object.title }}">
<img src="{{ object.image }}"  alt="" />
</a>
<p>{{ object.title}} from <a href="{{ object.url }}">{{ object.owner }}</a></p>
Thanks to <a href="http://pipes.yahoo.com/pipes/">Yahoo pipes</a> and <a href="http://www.flickr.com/">Flickr</a>
{% else %}
<img src="{{ STATIC_URL }}images/cats-computer-blue-screen-death.jpg" alt="" />

<p>From <a href="http://icanhascheezburger.com/">http://icanhascheezburger.com/</a></p>
{% endif %}

scampcat/templates/privacy.html
{% extends "base.html" %}
{% block title %}Privacy - {{ block.super }}{% endblock %}
{% block content %}
<h1>Privacy</h1>
{% endblock %}

scampcat/templates/terms.html
{% extends "base.html" %}
{% block title %}Terms - {{ block.super }}{% endblock %}
{% block content %}
<h1>Terms and Conditions</h1>
{% endblock %}